10:21:17.195 [main] ERROR com.cmc.exepciones.AdminClientes - No se encuentra el archivo
java.io.FileNotFoundException: C:\Users\AdminCMC\Downloads\Clientes3.txt (El sistema no puede encontrar la ruta especificada)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:211) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:153) ~[?:?]
	at java.io.FileReader.<init>(FileReader.java:75) ~[?:?]
	at com.cmc.exepciones.AdminClientes.armarCartera(AdminClientes.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:15) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
10:24:56.403 [main] ERROR com.cmc.exepciones.AdminClientes - No se encuentra el archivo
java.io.FileNotFoundException: C:\Users\AdminCMC\Downloads\Clientes3.txt (El sistema no puede encontrar la ruta especificada)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:211) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:153) ~[?:?]
	at java.io.FileReader.<init>(FileReader.java:75) ~[?:?]
	at com.cmc.exepciones.AdminClientes.armarCartera(AdminClientes.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:15) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
10:25:12.611 [main] ERROR com.cmc.exepciones.AdminClientes - No se encuentra el archivo
java.io.FileNotFoundException: C:\Users\AdminCMC\Downloads\Clientes3.txt (El sistema no puede encontrar la ruta especificada)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:211) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:153) ~[?:?]
	at java.io.FileReader.<init>(FileReader.java:75) ~[?:?]
	at com.cmc.exepciones.AdminClientes.armarCartera(AdminClientes.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:15) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
10:26:45.829 [main] ERROR com.cmc.exepciones.AdminClientes - No se encuentra el archivo
java.io.FileNotFoundException: C:\Users\AdminCMC\Downloads\Clientes3.txt (El sistema no puede encontrar la ruta especificada)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:211) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:153) ~[?:?]
	at java.io.FileReader.<init>(FileReader.java:75) ~[?:?]
	at com.cmc.exepciones.AdminClientes.armarCartera(AdminClientes.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:15) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
10:27:39.797 [main] ERROR com.cmc.exepciones.AdminClientes - Error al cerrar el archivo
com.cmc.exepciones.EvaluacionException: Caracter inv√°lido
	at com.cmc.exepciones.AdminClientes.armarcliente(AdminClientes.java:81) [classes/:?]
	at com.cmc.exepciones.AdminClientes.armarCartera(AdminClientes.java:44) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:15) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:03:12.304 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteA(TestColocarPrestamos.java:24) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:03:12.353 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteA(TestColocarPrestamos.java:24) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:03:12.354 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteA(TestColocarPrestamos.java:24) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:03:12.356 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteA(TestColocarPrestamos.java:24) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:03:12.358 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteA(TestColocarPrestamos.java:24) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:03:12.365 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteB(TestColocarPrestamos.java:35) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:03:12.367 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteB(TestColocarPrestamos.java:35) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:03:12.369 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteB(TestColocarPrestamos.java:35) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:03:12.371 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteB(TestColocarPrestamos.java:35) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:03:12.373 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteB(TestColocarPrestamos.java:35) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:06:39.959 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteA(TestColocarPrestamos.java:24) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:06:40.004 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteA(TestColocarPrestamos.java:24) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:06:40.006 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteA(TestColocarPrestamos.java:24) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:06:40.008 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteA(TestColocarPrestamos.java:24) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:06:40.011 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteA(TestColocarPrestamos.java:24) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:06:40.020 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteB(TestColocarPrestamos.java:35) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:06:40.022 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteB(TestColocarPrestamos.java:35) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:06:40.025 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteB(TestColocarPrestamos.java:35) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:06:40.027 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteB(TestColocarPrestamos.java:35) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
19:06:40.030 [main] ERROR com.cmc.exepciones.AdminPrestamos - Error al armar prestamo en la l√≠nea
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "this.prestamos" is null
	at com.cmc.evaluacion.fase2.entidades.Cliente.agregarPrestamo(Cliente.java:81) ~[classes/:?]
	at com.cmc.evaluacion.fase2.entidades.Cartera.colocarPrestamo(Cartera.java:40) ~[classes/:?]
	at com.cmc.exepciones.AdminPrestamos.armarPrestamo(AdminPrestamos.java:95) [classes/:?]
	at com.cmc.exepciones.AdminPrestamos.colocarPrestamos(AdminPrestamos.java:39) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteB(TestColocarPrestamos.java:35) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
